spring.application.name=diplomprojekt-uebungsprojekt-backend
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Execute DDL directly against the connected DB
spring.jpa.properties.jakarta.persistence.schema-generation.database.action=create

# Optionally export the generated scripts to disk simultaneously
spring.jpa.properties.jakarta.persistence.schema-generation.scripts.action=create
spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-target=src/sql/create-schema.sql
spring.jpa.properties.jakarta.persistence.schema-generation.scripts.drop-target=src/sql/drop-schema.sql
spring.jpa.properties.jakarta.persistence.schema-generation.create-source=metadata
spring.jpa.properties.jakarta.persistence.schema-generation.drop-source=metadata

app.storage.thumbnail-dir=./uploads/thumbnails
fastapi.thumbnail-service.url=http://localhost:8000